---
- name: install httpd
  hosts: all,!serverd
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: present
    - name: start and enable httpd
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    - name: add http to firewall
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: create index.html file
      copy:
        content: 'hello from nwkings'
        dest: /var/www/html/index.html

    - name: restart httpd
      service:
        name: httpd
        state: restarted
